name: Docs Check

on:
  pull_request:
  push:
    branches: [main]

jobs:
  build-docs:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: site
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - uses: ruby/setup-ruby@e65c17d16e57e481586a6a5a0282698790062f92 # v1
        with:
          ruby-version: '3.3'
          bundler-cache: true
          working-directory: site

      - name: Build docs
        run: bundle exec jekyll build --config _config.base.yml,_config.culture.yml -d _site_culture
        env:
          JEKYLL_ENV: production
